### ISSUE TITLE
kurkkulaulu  seko:00562   (throat singing as a voice instrument type)

### ISSUE THREAD

**Issue by jarmosaarikko** [jarmosaarikko/SEKO#17]
kurkkulaulu [seko:00562](http://urn.fi/urn:nbn:fi:au:seko:00562) - "throat singing"
-- Keski-Aasiassa, erityisesti Mongoliassa ja Tuvassa esiintyvä laulutapa, jonka avulla voidaan synnyttää kaksi samanaikaista ääntä. 
--  A singing method found in Central Asia, especially in Mongolia and Tuva, which can be used to produce two simultaneous voices.

in WIkidata is described as a singing methd in two concepts but there is no conept as a "voice" instrument.
- http://www.wikidata.org/entity/Q1067089 - throat singing - singing technique and vocal music
- http://www.wikidata.org/entity/Q691771 - overtone singing - singing technique and music genre
- http://www.wikidata.org/entity/Q109584422 - undertone singing - vocal technique and music genre
- https://en.wikipedia.org/wiki/Category:Throat_singing - list of pages
- several genres of throat singing are listed.

**throat singing** seems to be missing as a voice type  concept.

**Comment by jarmosaarikko** [comment]
comment received at Wikidata:
- Throat singing is definitely a vocal technique, and not a subtype of voice itself. Otherwise, along with "[male singing voice (Q54285279)](https://www.wikidata.org/wiki/Q54285279)" we could add "[death growl (Q335499)](https://www.wikidata.org/wiki/Q335499)" and [screaming (Q1932016)](https://www.wikidata.org/wiki/Q1932016) etc., which are also responsible for [vocal sound (Q4393922)](https://www.wikidata.org/wiki/Q4393922), not [voice type (Q1063547)](https://www.wikidata.org/wiki/Q1063547) or [type of musical instrument (Q110295396)](https://www.wikidata.org/wiki/Q110295396) and which are absolutely just as different from a normal voice as using a throat to sing. The instrument is voice, the others are techniques.

[See full discussion at Wikidata](https://www.wikidata.org/wiki/Topic:Xb43noqg7nmlcapu)

**Comment by jarmosaarikko** [comment]
Grove Music online ID "49849"  **Overtone-singing** [throat-singing, chant biphonique, chant diphonique, höömii]
- https://doi.org/10.1093/gmo/9781561592630.article.49849 --  (**PAYWALL**)

**Comment by MUUSA-kokous** [comment]
kurkkulaulu = throat singing

**Comment by jarmosaarikko** [comment]
Aikaisempi käsittely LUUMU-ryhmässä   https://wiki.helsinki.fi/display/LUUMU/Kokoukset+31-40
### Meeting: nro 33 22.5.2001

Lisäksi sovittiin, että hyväksytään termi **’kurkkulaulu’** sanastoon termin **’ääneslaulu’** korvaajaksi siitä huolimatta, että käsitettä määrittävät lähdejulkaisut (OIM, ’Suuri W&G’, New Grove jne.) suosivat jälkimmäistä tai siihen verrattavaa muunkielistä muotoa (esim. **’vocal harmonics’**). ’Kurkkulaulu’ vaikuttaa vakiintuneen yleiseen kielenkäyttöön tunnetuksi käsitteeksi riittävän selvästi.
