### ISSUE TITLE
bambusarja seko:00083 (percussion instrument)

### ISSUE THREAD

**Issue by jarmosaarikko** [jarmosaarikko/SEKO#26]
bambusarja [seko:00083](http://urn.fi/urn:nbn:fi:au:seko:00083)  _"bamboo series"_
- Useista bambusauvoista rakennettu lyömäsoitin.
- A percussion instrument built from several bamboo sticks

References, identifiers, sources and images needed.

**Comment by MUUSA-kokous** [comment]
Käsite voidaan poistaa.
